# Generated by Django 4.0.6 on 2022-07-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('befit_app', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
