# Generated by Django 4.0.6 on 2022-07-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('befit_app', '0003_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('calorie', models.FloatField(default=0)),
            ],
        ),
    ]
